# Generated by Django 2.1.1 on 2018-09-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('number_of_login', models.IntegerField()),
            ],
            options={
                'db_table': 'usersmodel',
            },
        ),
    ]
